# Generated by Django 4.2.5 on 2023-09-11 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must only contain letters and spaces', regex='^[a-zA-Z\\s]*$')]),
        ),
    ]
